openapi: 3.1.0
info:
  title: Hedera Mirror Node API
  description: API for retrieving public blockchain data from the Hedera Hashgraph network.
  version: 1.0.1
servers:
  - url: https://mainnet-public.mirrornode.hedera.com/api/v1
    description: Hedera Mirror Node Mainnet API
paths:
  /accounts:
    get:
      operationId: listBlockchainAccounts
      summary: Retrieve a list of blockchain accounts.
      description: Fetches a list of blockchain accounts on the Hedera network.
      responses:
        "200":
          description: A list of blockchain accounts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accounts:
                    type: array
                    items:
                      type: object
                      properties:
                        account:
                          type: string
                        balance:
                          type: integer
  /accounts/{idOrAliasOrEvmAddress}:
    get:
      operationId: fetchBlockchainAccountInfo
      summary: Retrieve public information about a blockchain account.
      description: Fetches general information for a blockchain account on the Hedera network.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Public account details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  account:
                    type: string
                  balance:
                    type: integer
                  evm_address:
                    type: string
                  alias:
                    type: string
  /accounts/{idOrAliasOrEvmAddress}/allowances/crypto:
    get:
      operationId: fetchHbarAllowances
      summary: Retrieve granted HBAR allowances.
      description: Retrieves information about HBAR allowances granted by an account.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of HBAR allowances.
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowances:
                    type: array
                    items:
                      type: object
                      properties:
                        spender:
                          type: string
                        amount:
                          type: integer
  /accounts/{idOrAliasOrEvmAddress}/rewards:
    get:
      operationId: fetchStakingRewards
      summary: Retrieve staking rewards history.
      description: Fetches past staking rewards payouts for a blockchain account.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of past staking rewards.
          content:
            application/json:
              schema:
                type: object
                properties:
                  rewards:
                    type: array
                    items:
                      type: object
                      properties:
                        amount:
                          type: integer
                        timestamp:
                          type: string
  /accounts/{idOrAliasOrEvmAddress}/airdrops/outstanding:
    get:
      operationId: fetchOutstandingAirdrops
      summary: Retrieve outstanding token airdrops.
      description: Fetches the list of outstanding token airdrops for a given blockchain account on the Hedera network.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of outstanding airdrops.
          content:
            application/json:
              schema:
                type: object
                properties:
                  airdrops:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        amount:
                          type: integer
  /accounts/{idOrAliasOrEvmAddress}/airdrops/pending:
    get:
      operationId: fetchPendingAirdrops
      summary: Retrieve pending token airdrops.
      description: Fetches the list of pending token airdrops for a given blockchain account on the Hedera network.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of pending airdrops.
          content:
            application/json:
              schema:
                type: object
                properties:
                  airdrops:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        amount:
                          type: integer
  /accounts/{idOrAliasOrEvmAddress}/allowances/tokens:
    get:
      operationId: fetchTokenAllowances
      summary: Retrieve granted token allowances.
      description: Retrieves information about token allowances granted by a blockchain account on the Hedera network.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of granted token allowances.
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowances:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        spender:
                          type: string
                        amount:
                          type: integer
  /accounts/{idOrAliasOrEvmAddress}/allowances/nfts:
    get:
      operationId: fetchNftAllowances
      summary: Retrieve granted NFT allowances.
      description: Retrieves information about NFT allowances granted by a blockchain account on the Hedera network.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of granted NFT allowances.
          content:
            application/json:
              schema:
                type: object
                properties:
                  allowances:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        spender:
                          type: string
                        serial_numbers:
                          type: array
                          items:
                            type: integer
  /accounts/{idOrAliasOrEvmAddress}/nfts:
    get:
      operationId: fetchOwnedNfts
      summary: Retrieve NFTs owned by a blockchain account.
      description: Fetches a list of NFTs associated with a given blockchain account on the Hedera network.
      parameters:
        - name: idOrAliasOrEvmAddress
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of owned NFTs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  nfts:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        serial_number:
                          type: integer
  /balances:
    get:
      operationId: fetchBlockchainBalances
      summary: Retrieve account balances.
      description: Fetches current blockchain account balances from the Hedera network.
      responses:
        "200":
          description: List of blockchain account balances.
          content:
            application/json:
              schema:
                type: object
                properties:
                  balances:
                    type: array
                    items:
                      type: object
                      properties:
                        account:
                          type: string
                        balance:
                          type: integer
  /tokens:
    get:
      operationId: listBlockchainTokens
      summary: Retrieve a list of tokens.
      description: Fetches a list of all tokens on the Hedera network.
      responses:
        "200":
          description: List of blockchain tokens.
          content:
            application/json:
              schema:
                type: object
                properties:
                  tokens:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        name:
                          type: string
                        symbol:
                          type: string
  /tokens/balances:
    get:
      operationId: fetchTokenBalances
      summary: Retrieve token balances across accounts.
      description: Fetches a list of token balances across multiple blockchain accounts on the Hedera network.
      responses:
        "200":
          description: List of token balances.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_balances:
                    type: array
                    items:
                      type: object
                      properties:
                        account:
                          type: string
                        token_id:
                          type: string
                        balance:
                          type: integer
  /tokens/{id}:
    get:
      operationId: fetchTokenInfo
      summary: Retrieve details of a token.
      description: Fetches metadata and details for a specific token by its ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Token details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_id:
                    type: string
                  name:
                    type: string
                  symbol:
                    type: string
                  total_supply:
                    type: integer
  /tokens/nfts:
    get:
      operationId: listBlockchainNfts
      summary: Retrieve a list of NFTs.
      description: Fetches a list of all NFTs available on the Hedera network.
      responses:
        "200":
          description: List of NFTs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  nfts:
                    type: array
                    items:
                      type: object
                      properties:
                        token_id:
                          type: string
                        serial_number:
                          type: integer
  /tokens/nfts/{serialNumber}:
    get:
      operationId: fetchNftDetails
      summary: Retrieve NFT details.
      description: Fetches metadata and details for a specific NFT by serial number.
      parameters:
        - name: serialNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: NFT details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_id:
                    type: string
                  serial_number:
                    type: integer
                  metadata:
                    type: string
  /tokens/nfts/{id}/transactions:
    get:
      operationId: fetchNftTransactions
      summary: Retrieve NFT transaction history.
      description: Fetches the transaction history for a specific NFT on the blockchain.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of NFT transactions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        transaction_id:
                          type: string
                        timestamp:
                          type: string
                        type:
                          type: string
  /topics/{topicId}:
    get:
      operationId: fetchTopicDetails
      summary: Retrieve details for a specific topic.
      description: Fetches public details for a given topic ID on the Hedera network.
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Topic details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  topic_id:
                    type: string
                  memo:
                    type: string
                  admin_key:
                    type: string
                  submit_key:
                    type: string
                  running_hash:
                    type: string
                  expiration_time:
                    type: string
  /topics/{topicId}/messages:
    get:
      operationId: fetchTopicMessages
      summary: Retrieve messages for a specific topic.
      description: Retrieves a list of messages associated with a given topic on the Hedera network.
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of topic messages.
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        sequence_number:
                          type: integer
                        consensus_timestamp:
                          type: string
                        message:
                          type: string
  /topics/{topicId}/messages/{sequenceNumber}:
    get:
      operationId: fetchTopicMessageBySequence
      summary: Retrieve a specific message from a topic by sequence number.
      description: Fetches a single message from a topic using its sequence number on the Hedera network.
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
        - name: sequenceNumber
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Topic message details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sequence_number:
                    type: integer
                  consensus_timestamp:
                    type: string
                  message:
                    type: string
  /topics/{topicId}/messages/{consensusTimestamp}:
    get:
      operationId: fetchTopicMessageByTimestamp
      summary: Retrieve a topic message by consensus timestamp.
      description: Retrieves a specific message from a topic using its consensus timestamp on the Hedera network.
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
        - name: consensusTimestamp
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Topic message details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sequence_number:
                    type: integer
                  consensus_timestamp:
                    type: string
                  message:
                    type: string
  /transactions:
    get:
      operationId: fetchBlockchainTransactions
      summary: Retrieve a list of blockchain transactions.
      description: Fetches a list of recent transactions on the Hedera network.
      responses:
        "200":
          description: List of blockchain transactions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      type: object
                      properties:
                        transaction_id:
                          type: string
                        consensus_timestamp:
                          type: string
                        transaction_type:
                          type: string
                        amount:
                          type: integer
                        sender:
                          type: string
                        receiver:
                          type: string
  /transactions/{id}:
    get:
      operationId: fetchTransactionDetails
      summary: Retrieve details of a blockchain transaction.
      description: Fetches metadata and details for a specific transaction on the Hedera network using its transaction ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaction details.
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                  consensus_timestamp:
                    type: string
                  transaction_type:
                    type: string
                  amount:
                    type: integer
                  sender:
                    type: string
                  receiver:
                    type: string
